### ISSUE TITLE
Upgrade to 8u181-jre-alpine3.8

### ISSUE THREAD

**Issue by DavidMoeremans** [openzipkin/docker-jre-full#11]
I would like to have the latest alpine:3.8 base.
This can be done by upgrading to the 8u181-jre-alpine3.8 tag of openjdk

I tried to push a tag as mention in the readme, but got a 403 :
>git tag -a 1.8.0_181 -m "update for 8u181-jre-alpine3.8"
>git push origin 1.8.0_181

**Comment by devinsba** [comment]
Right, only a contributor can push to the repo. If you create a pull request bumping the base image version we could try to get it merged in and released

**Comment by devinsba** [comment]
Updated to 1.8.0_191, not sure this addresses the alpine version or not. Please advise @DavidMoeremans

**Comment by nihaf** [comment]
Hi @devinsba,

yes, it does. The tag produced a Docker image based in the current `openjdk:8-jre-alpine`. I checked the image openzipkin/jre-full:1.8.0_191 with Clair. The result is
```
2019/01/22 12:00:47 [INFO] ▶ Image [openzipkin/jre-full:1.8.0_191] contains NO unapproved vulnerabilities
```
Thanks a lot! This issue could be marked as resolved, I think.

**Comment by DavidMoeremans** [comment]
Hi @devinsba,

yes indeed this solves the basic problem, it was indeed about the known vulnerabilities.
If you check now, btw it is based on alpine:3.8, so all good! 
thanks @nihaf @devinsba
