### ISSUE TITLE
build busted again :)

### ISSUE THREAD

**Issue by adriancole** [openzipkin/docker-jre-full#5]
@abesto mind saving us at some point? It isn't a huge rush https://travis-ci.org/openzipkin/docker-jre-full/builds/353326652

**Comment by abesto** [comment]
Wow. What even? It looks like... something changed in `docker-squash`? Maybe it's incompatible with the version of Python we use here?

Google to the rescue: we're hit by https://github.com/goldmann/docker-squash/issues/158. Lemme see, the workaround should be trivial.

**Comment by adriancole** [comment]
build is unbusted as we now use normal docker squash
