### ISSUE TITLE
Change parent image to openjdk:8-jdk-alpine?

### ISSUE THREAD

**Issue by alicefr** [openzipkin/docker-jre-full#7]
Hi,
I have a question and I hope you could help me.

I wanted to build `openzipkin/zipkin` docker image for another platform rather than `x86`. However, the `cantara/alpine-zulu-jdk8` has not multi-arch image support. So, I was wondering if it would be possible to change the parent image of [openzipkin/jre-full:](https://github.com/openzipkin/docker-jre-full/blob/master/Dockerfile) with the official docker image `openjdk:8-jdk-alpine`. The openjdk images has already multi-arch support. 

Thanks for the help!

**Comment by adriancole** [comment]
Thanks for the idea, Alice. I think the main issue is about the image size.. maybe with the current squashing approach we can handle that? Also, are you available to help with this?

**Comment by alicefr** [comment]
hi @adriancole. What are you concerns about the image size?The openjdk image size?
Because on my system (x86_64) the openjdk is smaller than cantara based image
```sh
$ docker pull cantara/alpine-zulu-jdk8
$ docker images | grep cantara
cantara/alpine-zulu-jdk8        latest                                     82d6c0ad442e        5 weeks ago         163MB

$ docker pull openjdk:8-jdk-alpine
$ docker images | grep openjdk
openjdk                         8-jdk-alpine                               224765a6bdbe        4 months ago        102MB
```

I'm glad to help you with that!

I saw that you use `docker-squash` command. Are you aware of the `squash` flag for [docker build](https://docs.docker.com/engine/reference/commandline/image_build/#options).
It is still an experimental flag, but it may help

**Comment by adriancole** [comment]
We get a lot of grief, often but not always from go folks, about the size
of our image. Also there are devs who work in low bandwidth scenarios and
having a small base layer helps a lot. Notably, this repo rips out the
"JDK" part leaving only the runtime. so if you look at this image it would
be smaller..

if it is even smaller after switch to openjdk that's be great.

PS I am not fresh on docker build goodies, so didn't know about that
experimental flag

**Comment by alicefr** [comment]
I will try to substitute the parent image and look at the size. If it is equal or smaller I can open a little PR with the changes. Is that ok for you?

**Comment by adriancole** [comment]
I await in anticipation, Alice!

**Comment by alicefr** [comment]
hi @adriancole! You find here my PR https://github.com/openzipkin/docker-jre-full/pull/8

**Comment by adriancole** [comment]
all good. thanks @alicefr!

Next up would be considering JRE 9 :)

**Comment by adriancole** [comment]
images are recut zipkin 2.7.4 is based on this
